package smsactivate

type Country struct {
	ID    int    `json:"id"`
	Code  string `json:"code"`
	Label string `json:"label"`
	Name  string `json:"name"`
}

var countryCatalog = []Country{
	{1, "UA", "乌克兰", "Ukraine"},
	{2, "KZ", "哈萨克斯坦", "Kazakhstan"},
	{3, "CN", "中国", "China"},
	{4, "PH", "菲律宾", "Philippines"},
	{5, "MM", "缅甸", "Myanmar"},
	{6, "ID", "印度尼西亚", "Indonesia"},
	{7, "MY", "马来西亚", "Malaysia"},
	{8, "KE", "肯尼亚", "Kenya"},
	{9, "TZ", "坦桑尼亚", "Tanzania"},
	{10, "VN", "越南", "Vietnam"},
	{11, "KG", "吉尔吉斯斯坦", "Kyrgyzstan"},
	{13, "IL", "以色列", "Israel"},
	{14, "HK", "中国香港", "Hong Kong"},
	{15, "PL", "波兰", "Poland"},
	{16, "GB", "英国", "United Kingdom"},
	{17, "MG", "马达加斯加", "Madagascar"},
	{18, "CD", "刚果民主共和国", "DR Congo"},
	{19, "NG", "尼日利亚", "Nigeria"},
	{20, "MO", "中国澳门", "Macao"},
	{21, "EG", "埃及", "Egypt"},
	{22, "IN", "印度", "India"},
	{23, "IE", "爱尔兰", "Ireland"},
	{24, "KH", "柬埔寨", "Cambodia"},
	{25, "LA", "老挝", "Laos"},
	{26, "HT", "海地", "Haiti"},
	{27, "CI", "科特迪瓦", "Ivory Coast"},
	{28, "GM", "冈比亚", "Gambia"},
	{29, "RS", "塞尔维亚", "Serbia"},
	{30, "YE", "也门", "Yemen"},
	{31, "ZA", "南非", "South Africa"},
	{32, "RO", "罗马尼亚", "Romania"},
	{33, "CO", "哥伦比亚", "Colombia"},
	{34, "EE", "爱沙尼亚", "Estonia"},
	{35, "AZ", "阿塞拜疆", "Azerbaijan"},
	{36, "CA", "加拿大", "Canada"},
	{37, "MA", "摩洛哥", "Morocco"},
	{38, "GH", "加纳", "Ghana"},
	{39, "AR", "阿根廷", "Argentina"},
	{40, "UZ", "乌兹别克斯坦", "Uzbekistan"},
	{41, "CM", "喀麦隆", "Cameroon"},
	{42, "TD", "乍得", "Chad"},
	{43, "DE", "德国", "Germany"},
	{44, "LT", "立陶宛", "Lithuania"},
	{45, "HR", "克罗地亚", "Croatia"},
	{46, "SE", "瑞典", "Sweden"},
	{47, "IQ", "伊拉克", "Iraq"},
	{48, "NL", "荷兰", "Netherlands"},
	{49, "LV", "拉脱维亚", "Latvia"},
	{50, "AT", "奥地利", "Austria"},
	{51, "BY", "白俄罗斯", "Belarus"},
	{52, "TH", "泰国", "Thailand"},
	{53, "SA", "沙特阿拉伯", "Saudi Arabia"},
	{54, "MX", "墨西哥", "Mexico"},
	{55, "TW", "中国台湾", "Taiwan"},
	{56, "ES", "西班牙", "Spain"},
	{57, "IR", "伊朗", "Iran"},
	{58, "DZ", "阿尔及利亚", "Algeria"},
	{59, "SI", "斯洛文尼亚", "Slovenia"},
	{60, "BD", "孟加拉国", "Bangladesh"},
	{61, "SN", "塞内加尔", "Senegal"},
	{62, "TR", "土耳其", "Turkey"},
	{63, "CZ", "捷克", "Czech"},
	{64, "LK", "斯里兰卡", "Sri Lanka"},
	{65, "PE", "秘鲁", "Peru"},
	{66, "PK", "巴基斯坦", "Pakistan"},
	{67, "NZ", "新西兰", "New Zealand"},
	{68, "GN", "几内亚", "Guinea"},
	{69, "ML", "马里", "Mali"},
	{70, "VE", "委内瑞拉", "Venezuela"},
	{71, "ET", "埃塞俄比亚", "Ethiopia"},
	{72, "MN", "蒙古", "Mongolia"},
	{73, "BR", "巴西", "Brazil"},
	{74, "AF", "阿富汗", "Afghanistan"},
	{75, "UG", "乌干达", "Uganda"},
	{76, "AO", "安哥拉", "Angola"},
	{77, "CY", "塞浦路斯", "Cyprus"},
	{78, "FR", "法国", "France"},
	{79, "PG", "巴布亚新几内亚", "Papua New Guinea"},
	{80, "MZ", "莫桑比克", "Mozambique"},
	{81, "NP", "尼泊尔", "Nepal"},
	{82, "BE", "比利时", "Belgium"},
	{83, "BG", "保加利亚", "Bulgaria"},
	{84, "HU", "匈牙利", "Hungary"},
	{85, "MD", "摩尔多瓦", "Moldova"},
	{86, "IT", "意大利", "Italy"},
	{87, "PY", "巴拉圭", "Paraguay"},
	{88, "HN", "洪都拉斯", "Honduras"},
	{89, "TN", "突尼斯", "Tunisia"},
	{90, "NI", "尼加拉瓜", "Nicaragua"},
	{91, "TL", "东帝汶", "Timor-Leste"},
	{92, "BO", "玻利维亚", "Bolivia"},
	{93, "CR", "哥斯达黎加", "Costa Rica"},
	{94, "GT", "危地马拉", "Guatemala"},
	{95, "AE", "阿联酋", "UAE"},
	{96, "ZW", "津巴布韦", "Zimbabwe"},
	{97, "PR", "波多黎各", "Puerto Rico"},
	{98, "SD", "苏丹", "Sudan"},
	{99, "TG", "多哥", "Togo"},
	{100, "KW", "科威特", "Kuwait"},
	{101, "SV", "萨尔瓦多", "El Salvador"},
	{102, "LY", "利比亚", "Libya"},
	{103, "JM", "牙买加", "Jamaica"},
	{104, "TT", "特立尼达和多巴哥", "Trinidad and Tobago"},
	{105, "EC", "厄瓜多尔", "Ecuador"},
	{106, "SZ", "斯威士兰", "Swaziland"},
	{107, "OM", "阿曼", "Oman"},
	{108, "BA", "波斯尼亚和黑塞哥维那", "Bosnia"},
	{109, "DO", "多米尼加共和国", "Dominican Republic"},
	{110, "SY", "叙利亚", "Syria"},
	{111, "QA", "卡塔尔", "Qatar"},
	{112, "PA", "巴拿马", "Panama"},
	{113, "CU", "古巴", "Cuba"},
	{114, "MR", "毛里塔尼亚", "Mauritania"},
	{115, "SL", "塞拉利昂", "Sierra Leone"},
	{116, "JO", "约旦", "Jordan"},
	{117, "PT", "葡萄牙", "Portugal"},
	{118, "BB", "巴巴多斯", "Barbados"},
	{119, "BI", "布隆迪", "Burundi"},
	{120, "BJ", "贝宁", "Benin"},
	{121, "BN", "文莱", "Brunei"},
	{122, "BS", "巴哈马", "Bahamas"},
	{123, "BW", "博茨瓦纳", "Botswana"},
	{124, "BZ", "伯利兹", "Belize"},
	{125, "CF", "中非共和国", "Central African Republic"},
	{126, "DM", "多米尼克", "Dominica"},
	{127, "GD", "格林纳达", "Grenada"},
	{128, "GE", "格鲁吉亚", "Georgia"},
	{129, "GR", "希腊", "Greece"},
	{130, "GW", "几内亚比绍", "Guinea-Bissau"},
	{131, "GY", "圭亚那", "Guyana"},
	{132, "IS", "冰岛", "Iceland"},
	{133, "KM", "科摩罗", "Comoros"},
	{134, "KN", "圣基茨和尼维斯", "Saint Kitts and Nevis"},
	{135, "LR", "利比里亚", "Liberia"},
	{136, "LS", "莱索托", "Lesotho"},
	{137, "MW", "马拉维", "Malawi"},
	{138, "NA", "纳米比亚", "Namibia"},
	{139, "NE", "尼日尔", "Niger"},
	{140, "RW", "卢旺达", "Rwanda"},
	{141, "SK", "斯洛伐克", "Slovakia"},
	{142, "SR", "苏里南", "Suriname"},
	{143, "TJ", "塔吉克斯坦", "Tajikistan"},
	{144, "MC", "摩纳哥", "Monaco"},
	{145, "BH", "巴林", "Bahrain"},
	{146, "RE", "留尼汪", "Reunion"},
	{147, "ZM", "赞比亚", "Zambia"},
	{148, "AM", "亚美尼亚", "Armenia"},
	{149, "SO", "索马里", "Somalia"},
	{150, "CG", "刚果共和国", "Congo"},
	{151, "CL", "智利", "Chile"},
	{152, "BF", "布基纳法索", "Burkina Faso"},
	{153, "LB", "黎巴嫩", "Lebanon"},
	{154, "GA", "加蓬", "Gabon"},
	{155, "AL", "阿尔巴尼亚", "Albania"},
	{156, "UY", "乌拉圭", "Uruguay"},
	{157, "MU", "毛里求斯", "Mauritius"},
	{158, "BT", "不丹", "Bhutan"},
	{159, "MV", "马尔代夫", "Maldives"},
	{160, "GP", "瓜德罗普", "Guadeloupe"},
	{161, "TM", "土库曼斯坦", "Turkmenistan"},
	{162, "GF", "法属圭亚那", "French Guiana"},
	{163, "FI", "芬兰", "Finland"},
	{164, "LC", "圣卢西亚", "Saint Lucia"},
	{165, "LU", "卢森堡", "Luxembourg"},
	{166, "VC", "圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines"},
	{167, "GQ", "赤道几内亚", "Equatorial Guinea"},
	{168, "DJ", "吉布提", "Djibouti"},
	{169, "AG", "安提瓜和巴布达", "Antigua and Barbuda"},
	{170, "KY", "开曼群岛", "Cayman Islands"},
	{171, "ME", "黑山", "Montenegro"},
	{172, "DK", "丹麦", "Denmark"},
	{173, "CH", "瑞士", "Switzerland"},
	{174, "NO", "挪威", "Norway"},
	{175, "AU", "澳大利亚", "Australia"},
	{176, "ER", "厄立特里亚", "Eritrea"},
	{177, "SS", "南苏丹", "South Sudan"},
	{178, "ST", "圣多美和普林西比", "Sao Tome and Principe"},
	{179, "AW", "阿鲁巴", "Aruba"},
	{180, "MS", "蒙特塞拉特", "Montserrat"},
	{181, "AI", "安圭拉", "Anguilla"},
	{182, "JP", "日本", "Japan"},
	{183, "MK", "北马其顿", "North Macedonia"},
	{184, "SC", "塞舌尔", "Seychelles"},
	{185, "NC", "新喀里多尼亚", "New Caledonia"},
	{186, "CV", "佛得角", "Cape Verde"},
	{187, "US", "美国", "USA"},
	{188, "PS", "巴勒斯坦", "Palestine"},
	{189, "FJ", "斐济", "Fiji"},
	{196, "SG", "新加坡", "Singapore"},
	{198, "WS", "萨摩亚", "Samoa"},
	{199, "MT", "马耳他", "Malta"},
	{200, "LI", "列支敦士登", "Liechtenstein"},
	{201, "GI", "直布罗陀", "Gibraltar"},
	{203, "XK", "科索沃", "Kosovo"},
	{204, "NU", "纽埃", "Niue"},
}

func Countries() []Country {
	return append([]Country(nil), countryCatalog...)
}

func countryExists(id int) bool {
	for _, country := range countryCatalog {
		if country.ID == id {
			return true
		}
	}
	return false
}
